export const bloodTestRanges = [
  { test: "HbA1c", unit: "mmol/mol", minimum: 20, maximum: 42 },
  {
    test: "Total Cholesterol",
    unit: "mmol/L",
    minimum: 2.5,
    maximum: 5.0,
  },
  { test: "HDL Cholesterol", unit: "mmol/L", minimum: 1.0, maximum: 2.0 },
  {
    test: "Non-HDL Cholesterol",
    unit: "mmol/L",
    minimum: 1.8,
    maximum: 3.8,
  },
  { test: "LDL Cholesterol", unit: "mmol/L", minimum: 1.0, maximum: 3.0 },
  {
    test: "Total Cholesterol:HDL Ratio",
    unit: null,
    minimum: 2.0,
    maximum: 5.0,
  },
  { test: "Triglyceride", unit: "mmol/L", minimum: 0.5, maximum: 1.7 },
  { test: "Urea", unit: "mmol/L", minimum: 2.8, maximum: 8.1 },
  { test: "Sodium", unit: "mmol/L", minimum: 136, maximum: 145 },
  { test: "Potassium", unit: "mmol/L", minimum: 3.5, maximum: 5.0 },
  { test: "Creatinine", unit: "µmol/L", minimum: 59, maximum: 104 },
  { test: "Albumin", unit: "g/L", minimum: 35, maximum: 50 },
  { test: "eGFR", unit: "mL/min/1.73m²", minimum: 90, maximum: null },
  { test: "Urinary Creatinine", unit: "mg/dL", minimum: 20, maximum: 370 },
  { test: "Microalbumin", unit: "mg/L", minimum: null, maximum: 30 },
  {
    test: "Microalbumin Creatinine Ratio",
    unit: "mg/g",
    minimum: null,
    maximum: 30,
  },
  { test: "Total Protein", unit: "g/L", minimum: 66, maximum: 87 },
  { test: "Total Bilirubin", unit: "µmol/L", minimum: 0, maximum: 21 },
  {
    test: "Alkaline Phosphatase",
    unit: "IU/L",
    minimum: 40,
    maximum: 129,
  },
  { test: "Gamma GT", unit: "IU/L", minimum: 10, maximum: 71 },
  { test: "AST", unit: "IU/L", minimum: 0, maximum: 40 },
  {
    test: "Alanine Transaminase",
    unit: "IU/L",
    minimum: 0,
    maximum: 41,
  },
  { test: "Urate", unit: "µmol/L", minimum: 200, maximum: 430 },
];
